apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: lb
          image: miguelgrinberg/easy-lb-haproxy
          env:
            - name: ETCD_PEERS
              value: http://etcd0:2379,http://etcd1:2379,http://etcd2:2379
            - name: HAPROXY_STATS
              value: "1"
          ports:
            - containerPort: 80
