apiVersion: v1
kind: Service
metadata:
  name: messages
spec:
  selector:
    app: messages
  ports:
    - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: messages
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages
          image: miguelgrinberg/microflack_messages
          ports:
            - containerPort: 5000
          env:
            - name: ETCD
              value: http://etcd0:2379,http://etcd1:2379,http://etcd2:2379
            - name: REDIS
              value: redis:6379
            - name: LB
              value: http://lb
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app
                  key: key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app
                  key: jwtkey
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: messages

